#--build and run
#docker-compose up --build

#--connection via node container
#mysql -h <DATABASE_SEVERICE_NAME> -u <DATA_BASE_USER> -P <EXPOSED PORT> -p <ROOT_PASS>

#--connection via host
#mysql -h 127.0.0.1 -u <DATA_BASE_USER> -P <EXPOSED PORT> -p <ROOT_PASS>

version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
  app:
    environment:
      - NODE_ENV=dev
    ports:
      - "7304:7304"
    build:
      context: .
    #calling the mysql health script and then starting the express server
    command: ["bash", "./dbwait-script.sh"]
